### PR TITLE
Performance improvements to exportation process

### PR DESCRIPTION
**Pull request by meritzio**
- Reduced dictionary key sizes by storing face nodes as ordered integer tuples instead of strings.
   For example:
        + An internal triangle face of nodes 21, 24, 23 would previously have the string key '[21, 23, 24]' 
           which features redundant key characters '[', ']' , ',' and ' ' .
        + By using a sorted tuple instead of sorted string list - (21, 23, 24), overhead is reduced by 
            eliminating the previous redundant characters

- Reduced number of Salome calls by buffering to improve performance:
        + Originally the conversion algorithm would [loop count the number of faces](https://github.com/nicolasedh/salomeToOpenFOAM/blob/d9ada94842fe4038e58be6f4c5f7cbbbdae97367/salomeToOpenFOAM.py#L115-L117), and repeat this call later in the program, requiring multiple calls [downstream](https://github.com/nicolasedh/salomeToOpenFOAM/blob/d9ada94842fe4038e58be6f4c5f7cbbbdae97367/salomeToOpenFOAM.py#L233-L238) in the main section
       + To reduce multiple calls such as this, a class [MeshBuffer](https://github.com/meritzio/salomeToOpenFOAM/blob/99216dd9ceddda1b693f7c4ca328009bf2e63088/salomeToOpenFOAM.py#L56-L86) has been introduced for each mesh volume, storing the element face nodes, which also immediately generates the redesigned sorted key for each face to reduce the amount of key conversion overhead. For baffle support, the reverse key (and normal key) follows the same principle, and the key function is accessed via [the static methods](https://github.com/meritzio/salomeToOpenFOAM/blob/99216dd9ceddda1b693f7c4ca328009bf2e63088/salomeToOpenFOAM.py#L77-L86) of the MeshBuffer class

### CODE REVIEW

**Comment by nicolasedh** [comment]
Thanks for the contribution! This sounds great I'll give it a try later tonight.

Best regards
Nicolas

**Comment by meritzio** [comment]
Happy to help!

I have ran some SHA256 checksums on meshes exported from the original script and this one to ensure that the mesh files produced are exactly the same... As well as running checkMesh in OpenFOAM and simulating with the output meshes :)

I have only made some small changes, so if you do some profiling on a large mesh you should see the time differences. It's somewhere around a quarter to a third faster with my checks on windows; so not that much faster, but a 1 hour export becoming 45 mins is convenient for me!

**Comment by nicolasedh** [comment]
Hi!

I had a look at the code and was about to test it but instead ended up with
trying to install Salome version 8.3 which somehow don't play nice on
Ubuntu 17.04. something about protobuf not being the right version although
the installed version is the correct one... I'm giving up for the night.
I'll install an older version of Salome and try your code out. Then merge
it. Seems like really good work!

3/4 improvement is still great! But to be honest 45 min for a 1M mesh is
way to much. I wish I had the time to improve the algorithm. :-(. I saw
that there is an hdf5 exporter in 8.3. I haven't tried it but did start to
work on a foamToHdf5 app. Maybe that would be the way to go :-)

Bets regards
Nicolas

Den 7 dec. 2017 19:00 skrev "Samuel Woodhead" <notifications@github.com>:

**Comment by nicolasedh** [comment]
I had an idea. 

The reason for the low performance I think is the use of a dictionary to look up which faces we traversed. As we loop over all cells we add them to either one of the lists owner or neighbour. And we need to know if the current cell is an owner or a neigbour. The current solution is to have a dictionary where the keys are the points of the face, e.g. "(1 3 4 51)". Dictionary lookups are quite fast but in this case way to slow.

Another way to accomplish the same thing would be to have a lboolean ist, traversedPoints. It would have the same length as the number of points, all elements would initially be false. Now when add a face we would set traversedPoints to True for all points belonging to that face. We know a cell is a neighbor to a face when all points of that face are true in traversedPoints.

I think this would be way faster than the current method. But sadly I don't have time to implement this right now. These days my son and newborn is talking almost all of my spare time. =)

Let me know if you are interested to work with this idea. I would be happy help with ideas.
/Nicolas

**Comment by meritzio** [comment]
Hi Nicolas,

Your idea could bring the time down a bit as it prevents spending time having to sort, prepare the tuples and compare hashes. In addition, you would have the added benefit of knowing the answer as soon as a false is encountered.

Last week I ran a profile of the function calls using the python standard module cProfile (Profile class) and it seemed that most of the time is spent in the _omnipy.invoke method, called from GetElemFaceNodes, so after this next alteration I think the bottleneck will be focused on how we can limit the number of API calls. I looked into the documentation to try and return an array of face nodes in a single call [instead of looping and calling GetElemFaceNodes multiple times](https://github.com/nicolasedh/salomeToOpenFOAM/blob/680586dafc69bec44118c435dff2605495cf4bac/salomeToOpenFOAM.py#L65-L70) but I couldn't find one... although I haven't looked too thoroughly!

Congratulations on your newborn :)

I'll give it a trial and send the results your way. I'm not sure how busy I am going to be but I'll try to get an implementation ready this week.

Kind Regards,
Sam.

**Comment by nicolasedh** [comment]
That sounds great!

I'm quite certain I'm (we're ?) doing something fundamentally wrong since
at 2M cells generation is actually faster than export :-o . There is room
for improvement ! :-)

Den 12 dec. 2017 00:34 skrev "Samuel Woodhead" <notifications@github.com>:

**Pull request merged**
